# Generated by Django 2.2.9 on 2021-10-20 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a9aaadb-ff3e-4505-80de-9230da25367a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
