# Generated by Django 2.2.9 on 2021-10-20 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211020_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('103d57ac-7538-45ff-a875-4f9e13a1129e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set(),
        ),
    ]
