# Generated by Django 2.2.9 on 2021-10-20 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211020_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34babece-b2bc-4305-b0c9-94099a0465fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
