# Generated by Django 2.2.9 on 2021-10-20 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211020_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2360e1a1-6ea8-41c7-bcc6-8ca35fab1f58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
